name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Permite compilar manualmente desde la pestaña de Actions en GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configuramos el entorno de Gradle forzando una versión compatible (Gradle 8.4)
    # con nuestro Android Gradle Plugin (8.2.2) para evitar errores de compatibilidad.
    - name: Configurar Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.4'

    # Ejecutamos la compilación usando la versión de Gradle 8.4 establecida anteriormente
    - name: Compilar APK con Gradle 8.4
      run: gradle assembleDebug

    - name: Subir Archivo APK como Artefacto
      uses: actions/upload-artifact@v4
      with:
        name: checkealo-app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
